package service






























































}	return s.repo.SoftDelete(id)	}		return errors.ErrNotFound	if _, err := s.repo.GetByID(id); err != nil {func (s *deviceService) SoftDelete(id uint) error {}	return dbDevice, nil	}		return nil, err	if err := s.repo.Update(dbDevice); err != nil {	dbDevice.IsActive = device.IsActive	dbDevice.Location = device.Location	dbDevice.IP = device.IP	dbDevice.Hostname = device.Hostname	}		return nil, errors.ErrNotFound	if err != nil {	dbDevice, err := s.repo.GetByID(id)func (s *deviceService) Update(id uint, device *model.Device) (*model.Device, error) {}	return s.repo.List(isActive, hostname)func (s *deviceService) List(isActive *bool, hostname *string) ([]model.Device, error) {}	return d, nil	}		return nil, errors.ErrNotFound	if err != nil {	d, err := s.repo.GetByID(id)func (s *deviceService) GetByID(id uint) (*model.Device, error) {}	return s.repo.Create(device)func (s *deviceService) Create(device *model.Device) error {}	return &deviceService{repo: repo}func NewDeviceService(repo repository.DeviceRepository) DeviceService {}	repo repository.DeviceRepositorytype deviceService struct {}	SoftDelete(id uint) error	Update(id uint, device *model.Device) (*model.Device, error)	List(isActive *bool, hostname *string) ([]model.Device, error)	GetByID(id uint) (*model.Device, error)	Create(device *model.Device) errortype DeviceService interface {)	"github.com/islamchupanov/tz1/internal/repository"	"github.com/islamchupanov/tz1/internal/model"	"github.com/islamchupanov/tz1/internal/errors"import (package service